root = "."
tmp_dir = "tmp_b"

[build]
cmd = "go build -o ./tmp/main_event_b ./cmd/function/event/main.go"
bun = "./tmp/main_event_b"
full_bin = "./tmp/main_event_b"
include_ext = ["go", "tpl", "tmpl"]
exclude_dir = ["./tmp", "./db"]
log = "air_event_a.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = true
kill_delay = 500 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
